kind: pipeline
name: default

steps:
- name: build  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_name
    password:
      from_secret: docker_password
    repo: mindrot/news
